db-uri = "postgresql://postgres@localhost:5432/db_chuichun"
db-schema = "public"
db-anon-role = "postgres"
db-pool = 10
server-port = 3000
server-host = "localhost"

# CORS settings
server-cors-origins = "http://localhost:3001"

# API settings
max-rows = 1000
